[package]
name = "bevy_github_ci_template"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = { version = "0.8", features = ["dynamic"] }
bevy-inspector-egui = "0.12.1"
bytemuck = "1.12.1"
noise = "0.7.0"
[profile.dev.package."*"]
opt-level = 3
